(define factoryFloor (vector
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o '0 '0 '0 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o '0 '0 '0 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'S 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
))
