(define factoryFloor (vector
    (vector 'o 'A 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o '0 '0 '0 'o)
    (vector 'o 'i 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o '0 '0 '0 'o)
    (vector 'o 'S 'o 'P 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
    (vector 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o 'o)
))
