(define (assert-that testDescription input expectedOut)
    (if (= test expectedOut)
        (display "Test passed: ")
        (display "Test failed: ")
    )
    (display testDescription)
    (newline)
    (display "Result was: ")
    (display expectedOut)
    (newline)
)
